### ISSUE TITLE
Use OAuth in website

### ISSUE THREAD

**Issue by vovs03** [ruby-social/issues#1]
# Why don't use it?

See official web-site of [ruby-social](https://ruby.social/)

- [ ] OAuth application for login.

**Comment by lazyatom** [comment]
Applications can use OAuth to authentication against Mastodon, including the https://ruby.social instance. What other use were you thinking about?

**Comment by vovs03** [comment]
@lazyatom I don't using Mastodon. And the [site](https://ruby.social/) does not invite me to pass through the authentication through githab

**Comment by lazyatom** [comment]
Oh, so you want to be able to log in using GitHub? I'm afraid that's an issue that's more appropriate for https://github.com/tootsuite/mastodon
